title: cleaker
description: Namespace identity resolver.
url: https://neurons-me.github.io
baseurl: "/Cleaker"

remote_theme: neurons-me/neurons-me

plugins:
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false

exclude:
  - Typescript/node_modules
  - Python/__pycache__
  - Rust/target
  - Typescript/dist
  - Typescript/dist-types
  - Typescript/src
  - Typescript/tests
  - node_modules
  - "*/node_modules"
  - vendor

me_theme:
  brand: cleaker
  favicon: "https://res.cloudinary.com/dkwnxf6gm/image/upload/v1778177581/ChatGPT_Image_May_7_2026_12_12_28_PM_xzkwtc.png"
  nav:
    - label: Home
      url: https://neurons-me.github.io/
    - label: Docs
      relative_url: /docs/
    - label: Github
      url: https://github.com/neurons-me/cleaker
    - label: All.This
      url: https://neurons-me.github.io/all.this/
